// <auto-generated />
using ABNLookup.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ABNLookup.Infrastructure.Migrations
{
    [DbContext(typeof(AbnContext))]
    [Migration("20200518223612_AbnContextInitialCreate")]
    partial class AbnContextInitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ABNLookup.Domain.Models.Abn", b =>
                {
                    b.Property<long>("ClientInternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ABNidentifierValue")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientInternalId");

                    b.HasIndex("ABNidentifierValue")
                        .IsUnique();

                    b.ToTable("Abn");
                });
#pragma warning restore 612, 618
        }
    }
}
